### ISSUE TITLE
UTC Module not found

### ISSUE THREAD

**Issue by aebian** [ronilaukkarinen/pager#1]
Maybe I'm just dump but:

<code>

 14:49  Can't locate Time/Duration.pm in @INC (you may need to install the Time::Duration module) (@INC contains: /home/Dead//.irssi/scripts /usr/share/irssi/scripts
          /usr/lib/x86_64-linux-gnu/perl/5.20 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5
          /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/Dead//.irssi/scripts/autorun/pager.pl line 2.
 14:49  BEGIN failed--compilation aborted at /home/Dead//.irssi/scripts/autorun/pager.pl line 2.

</code>

I'm not able to figure out where i can download that module.
The pager thing should also standalone (with utc module). So don't need Bitlbee ect. right?

Cheers,

Alex

**Comment by rollecode** [comment]
This is yet a bit under construction by its documentation, but the script requires perl's `Time::Duration` which can be installed with your package manager or `sudo cpan install Time::Duration` or from [cpan.org](http://search.cpan.org/~avif/Time-Duration/Duration.pm).

Bitlbee is not needed for this script.

**Comment by aebian** [comment]
Okay works,

does this also work wit the auto away scripts?
Thanks so far,

A.

**Comment by rollecode** [comment]
Yes, it should work.
